config/routes.rb
Rails.application.routes.draw do
  resources :authors do
    resources :books
  end

  root 'authors#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
  validates :name, :email, :presence => true
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  validates :title, :author, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def edit
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to @author, notice: 'Author was successfully created.'
    else
      render :new
    end
  end

  def update
    if @author.update(author_params)
      redirect_to @author, notice: 'Author was successfully updated.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :email, :phone, :country)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_author
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = @author.books
  end

  def new
    @book = @author.books.new
  end

  def edit
  end

  def create
    @book = @author.books.new(book_params)
    if @book.save
      redirect_to author_books_url, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to author_books_url, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  private
    def set_book
      @book = @author.books.find_by_id(params[:id])
      redirect_to author_books_url(@author), :alert => "Book can't be found." unless @book
    end

    def book_params
      params.require(:book).permit(:title, :description)
    end

    def set_author
      @author = Author.find(params[:author_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<div class="row">
    <div class="col-md-8">
        <%= form_for(@author) do |f| %>
            <% errors = @author.errors %>
            <div class="form_item">
                <%= f.label :name %>
                <%= f.text_field :name, :class => "form-control" %>

                <% if errors.present? && errors[:name].present? %>
                    <div class="error">
                        <%= errors[:name][0] %>
                    </div>
                <% end %>
            </div>

            <div class="form_item">
                <%= f.label :email %>
                <%= f.text_field :email, :class => "form-control" %>

                <% if errors.present? && errors[:email].present? %>
                    <div class="error">
                        <%= errors[:email][0] %>
                    </div>
                <% end %>
            </div>

            <div class="form_item">
                <%= f.label :phone %>
                <%= f.text_field :phone, :class => "form-control" %>
            </div>

            <div class="form_item">
                <%= f.label :country %>
                <%= f.text_field :country, :class => "form-control" %>
            </div>

            <div class="form_item control-group clearfix">
                <div class="pull-left link_item">
                    <%= f.submit @author.persisted? ? "Update" : "Create", :class => "btn btn-primary" %>
                </div>

                <div class="pull-left link_item">
                    <%= link_to "Back", authors_path, :class => "btn btn-info"  %>
                </div>
            </div>

        <% end %>
    </div>
</div>

app/views/authors/edit.html.erb
<h3>Edit an author</h3>
<%= render 'form' %>

app/views/authors/index.html.erb
<div class="btn-wrapp">
    <%= link_to 'Add new author', new_author_path, :class => "btn btn-primary" %>
</div>

<h3>
    Listing Authors
</h3>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Country</th>
            <th>Books</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <% @authors.each do |author| %>
            <tr>
                <td>
                    <%= link_to author.name, author_path(author)  %>
                </td>
                <td>
                    <%= author.email %>
                </td>
                <td>
                    <%= author.phone %>
                </td>
                <td>
                    <%= author.country %>
                </td>
                <td>
                    <%= link_to "View", author_books_path(author) %>
                </td>
                <td>
                    <%= link_to 'Edit', edit_author_path(author), :class => "btn btn-info btn-sm" %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/authors/new.html.erb
<h3>New author</h3>
<%= render 'form' %>

app/views/authors/show.html.erb
<div class="row">
    <div class="col-md-8">
        <div class="data_item">
            <strong>Name:</strong>
            <%= @author.name %>
        </div>

        <div class="data_item">
            <strong>Email:</strong>
            <%= @author.email %>
        </div>

        <div class="data_item">
            <strong>Phone:</strong>
            <%= @author.phone %>
        </div>

        <div class="data_item">
            <strong>Country:</strong>
            <%= @author.country %>
        </div>

        <div class="form_item control-group clearfix">
            <div class="pull-left link_item">
                <%= link_to 'Edit', edit_author_path(@author), :class => "btn btn-info" %>
            </div>

            <div class="pull-left link_item">
                <%= link_to 'Back', authors_path, :class => "btn btn-primary" %>
            </div>
        </div>
    </div>
</div>

app/views/books/_form.html.erb
<div class="row">
    <div class="col-md-8">
        <%= form_for ([@author, @book]) do |f| %>
            <% errors = @book.errors %>
            <div class="form_item">
                <%= f.label :title %>
                <%= f.text_field :title, :class => "form-control" %>

               <% if errors.present? && errors[:title].present? %>
                    <div class="error">
                        <%= errors[:title][0] %>
                    </div>
                <% end %>
            </div>

            <div class="form_item">
                <%= f.label :description %><br>
                <%= f.text_area :description, :class => "form-control", :rows => 6 %>
            </div>

            <div class="form_item control-group clearfix">
                <div class="pull-left link_item">
                    <%= f.submit @book.persisted? ? "Update" : "Create", :class => "btn btn-primary" %>
                </div>

                <div class="pull-left link_item">
                    <%= link_to "Back", author_books_path(@author), :class => "btn btn-info"  %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/books/edit.html.erb
<h2>Editing Book of <%= @author.name %></h2>

<%= render 'form' %>

app/views/books/index.html.erb
<div class="btn-wrapp">
    <%= link_to 'Add new book', new_author_book_path(@author), :class => "btn btn-primary" %>
</div>
<h3>Books of <%= @author.name %></h3>

<% if @books.empty? %>
    <div class="alert alert-warning">
        No books found.
    </div>
<% else %>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
            <% @books.each do |book| %>
                <tr>
                    <td><%= book.title %></td>
                    <td><%= book.description %></td>
                    <td><%= link_to 'Edit', edit_author_book_path(@author, book) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

<div class="form_item control-group clearfix">
    <div class="pull-left link_item">
        <%= link_to 'Back', authors_path, :class => "btn btn-primary" %>
    </div>
</div>

app/views/books/new.html.erb
<h3>New book for <%= @author.name %></h3>

<%= render 'form' %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>References:</strong>
  <%= @book.references %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation">
              <%= link_to "Home", authors_path  %>
            </li>
            <li role="presentation">
              <%= link_to "Add new author",new_author_path  %>
            </li>
          </ul>
        </nav>
        <h3 class="text-muted">Book Store</h3>
      </div>
      <div class="body-content">
        <% if alert.present? %>
          <div class="alert alert-danger">
            <%= alert %>
          </div>
        <% end %>

        <% if notice.present? %>
          <div class="alert alert-info">
            <%= notice %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>